# Generated by Django 4.1.2 on 2023-01-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_utspbo", "0009_remove_jurnal_foto_jurnal_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="bulan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bulan", models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name="harga_ikan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harga_ikan", models.CharField(max_length=54)),
            ],
        ),
        migrations.RenameModel(old_name="nama_latin", new_name="lokasi_tpi",),
        migrations.RenameField(
            model_name="jurnal", old_name="email_penerbit", new_name="email_petugas",
        ),
        migrations.RenameField(
            model_name="jurnal", old_name="penerbit", new_name="jenis_ikan",
        ),
        migrations.RenameField(
            model_name="jurnal", old_name="jumlah_halaman", new_name="jumlah_ikan",
        ),
        migrations.RenameField(
            model_name="jurnal", old_name="nama_latin", new_name="lokasi_tpi",
        ),
        migrations.RenameField(
            model_name="jurnal", old_name="judul", new_name="nama_petugas",
        ),
        migrations.RenameField(model_name="jurnal", old_name="penulis", new_name="no",),
        migrations.RenameField(
            model_name="jurnal", old_name="tahun_terbit", new_name="tahun",
        ),
        migrations.RenameField(
            model_name="lokasi_tpi", old_name="nama_latinn", new_name="lokasi_tpi",
        ),
        migrations.RemoveField(model_name="jurnal", name="kampus",),
        migrations.RemoveField(model_name="jurnal", name="kelompok_ikan",),
        migrations.DeleteModel(name="Kampus",),
        migrations.DeleteModel(name="Kelompok_ikan",),
        migrations.AddField(
            model_name="jurnal",
            name="bulan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_utspbo.bulan",
            ),
        ),
        migrations.AddField(
            model_name="jurnal",
            name="harga_ikan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_utspbo.harga_ikan",
            ),
        ),
    ]
