# Generated by Django 4.1.5 on 2023-01-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_utspbo", "0011_peta"),
    ]

    operations = [
        migrations.CreateModel(
            name="alattangkap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=50)),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="lagu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namakapten", models.CharField(max_length=100)),
                ("jenisikan", models.CharField(max_length=100)),
                ("tanggalberangkat", models.CharField(max_length=100)),
                ("jumlah", models.IntegerField(null=True)),
                ("img", models.CharField(max_length=40, null=True)),
                (
                    "alattangkap",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_utspbo.alattangkap",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="jurnal",
            name="bulan",
        ),
        migrations.RemoveField(
            model_name="jurnal",
            name="harga_ikan",
        ),
        migrations.RemoveField(
            model_name="jurnal",
            name="lokasi_tpi",
        ),
        migrations.RemoveField(
            model_name="peta",
            name="nama_lokasi",
        ),
        migrations.RemoveField(
            model_name="peta",
            name="no",
        ),
        migrations.RemoveField(
            model_name="peta",
            name="titik_koordinat",
        ),
        migrations.AddField(
            model_name="peta",
            name="jumlah",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="peta",
            name="koordinat",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="peta",
            name="deskripsi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="bulan",
        ),
        migrations.DeleteModel(
            name="harga_ikan",
        ),
        migrations.DeleteModel(
            name="Jurnal",
        ),
        migrations.DeleteModel(
            name="lokasi_tpi",
        ),
    ]
